name: Test Template v1.0.0

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular pruebas
        run: echo "Tests ejecutados correctamente"